---
redir-port: 7891
tproxy-port: 7892
port: 8080
socks-port: 1080
mixed-port: 7890
mode: rule
log-level: silent
allow-lan: true
ipv6: true
external-ui: "/usr/share/openclash/ui"
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
tcp-concurrent: true
unified-delay: true
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  mmdb: https://github.com/malikshi/geoip/raw/refs/heads/release/Country.mmdb
  geoip: https://github.com/malikshi/v2ray-rules-dat/raw/refs/heads/release/geoip.dat
  geosite: https://github.com/malikshi/v2ray-rules-dat/raw/refs/heads/release/geosite.dat
global-client-fingerprint: chrome
keep-alive-interval: 15
keep-alive-idle: 600
disable-keep-alive: true
find-process-mode: 'off'
hosts:
  localhost:
  - 127.0.0.1
  - ::1
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:1053
  respect-rules: true
  prefer-h3: true
  use-system-hosts: true
  use-hosts: true
  nameserver:
  - https://dns.cloudflare.com/dns-query#ALL-GROUP&h3=true
  - tls://one.one.one.one#ALL-GROUP
  - 1.1.1.1#ALL-GROUP
  - "[2606:4700:4700::1111]#ALL-GROUP"
  fallback:
  - https://dns.cloudflare.com/dns-query#ALL-GROUP&h3=true
  - tls://one.one.one.one#ALL-GROUP
  - 1.0.0.1#ALL-GROUP
  - "[2606:4700:4700::1001]#ALL-GROUP"
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - "[2606:4700:4700::1111]"
  - "[2606:4700:4700::1001]"
  proxy-server-nameserver:
  - https://dns.cloudflare.com/dns-query#ALL-GROUP&h3=true
  - tls://one.one.one.one#ALL-GROUP
  - 1.0.0.1#ALL-GROUP
  - 1.1.1.1#ALL-GROUP
  - "[2606:4700:4700::1111]#ALL-GROUP"
  - "[2606:4700:4700::1001]#ALL-GROUP"
  - 1.1.1.1
  - 1.0.0.1
  - "[2606:4700:4700::1001]"
  - "[2606:4700:4700::1111]"
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
  sniff:
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
  - "+"
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - dlg.io.mi.com
  - "+.oray.com"
  - "+.sunlogin.net"
  - "+.push.apple.com"
tun:
  enable: true
  stack: gvisor
  device: utun
  dns-hijack:
  - tcp://any:53
  gso: true
  gso-max-size: 65536
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
  store-fake-ip: true
proxy-groups:
- name: ALL-GROUP
  type: select
  disable-udp: false
  proxies:
  - Traffic-Browsing
  - Traffic-Porn
  - Traffic-Ads
  - Traffic-Gaming
  - BEST-PING
  - FALLBACK
  - LB
  - DIRECT
  use:
  - Akun
  url: https://captive.apple.com/generate_204
  interval: 60
- name: Traffic-Browsing
  type: select
  disable-udp: false
  proxies:
  - FALLBACK
  - LB
  use:
  - Akun
- name: Traffic-Gaming
  type: select
  disable-udp: false
  proxies:
  - FALLBACK
  - LB
  use:
  - Akun
- name: Traffic-Porn
  type: select
  disable-udp: false
  proxies:
  - Traffic-Browsing
  - REJECT
- name: Traffic-Ads
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - Traffic-Browsing
- name: LB
  type: load-balance
  disable-udp: false
  strategy: consistent-hashing
  use:
  - Akun
  url: https://captive.apple.com/generate_204
  interval: 180
- name: BEST-PING
  type: url-test
  disable-udp: false
  lazy: false
  use:
  - Akun
  url: https://captive.apple.com/generate_204
  interval: 180
- name: FALLBACK
  type: fallback
  disable-udp: false
  use:
  - Akun
  url: https://captive.apple.com/generate_204
  interval: 180
proxy-providers:
  Akun:
    type: file
    path: "./proxy_provider/Akun.yaml"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 180
rule-providers:
  oisd_big:
    type: http
    behavior: classical
    path: "./rule_provider/oisd_big.yaml"
    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/oisd_big.yaml
    interval: 14400
rules:
- MATCH,ALL-GROUP
- AND,((NETWORK,udp),(OR,(DST-PORT,443),(GEOSITE,youtube))),REJECT
- GEOSITE,rule-malicious,REJECT,no-resolve
- RULE-SET,oisd_big,Traffic-Ads,no-resolve
- GEOSITE,oisd-full,Traffic-Ads
- GEOSITE,d3ward,Traffic-Ads
- GEOSITE,rule-ads,Traffic-Ads
- NOT,((DOMAIN-SUFFIX,googlesyndication.com)),Traffic-Ads
- GEOSITE,oisd-nsfw,Traffic-Porn
- GEOIP,GOOGLE,Traffic-Browsing
- GEOSITE,GOOGLE,Traffic-Browsing
- AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,(DOMAIN-KEYWORD,google))),Traffic-Browsing
- AND,((NETWORK,UDP),(DST-PORT,5228-5230),(OR,(DOMAIN-KEYWORD,google))),Traffic-Browsing
- GEOSITE,rule-gaming,Traffic-Gaming
- GEOSITE,rule-indo,Traffic-Browsing
- GEOSITE,rule-sosmed,Traffic-Browsing
- GEOSITE,rule-streaming,Traffic-Browsing
- GEOSITE,rule-speedtest,Traffic-Browsing
- GEOSITE,videoconference,Traffic-Browsing
- GEOIP,id,Traffic-Browsing
- GEOIP,facebook,Traffic-Browsing
- GEOIP,telegram,Traffic-Browsing
- GEOIP,cloudflare,DIRECT
- GEOIP,cloudfront,DIRECT

