#!/bin/sh

VID=$(cat /sys/bus/usb/devices/*/idVendor)
VIDS=("1d6b" "0bda" "2cb7" "1199" "8087" "413c" "1bc7" "03f0")
if [ "$VID" = "$VIDS" ]; then
	logger "USB WiFi device plugged in"
	# Config WiFi
	/usr/bin/hat.sh >/dev/null 2>&1
	/usr/bin/wifi.sh >/dev/null 2>&1
fi
