#!/bin/sh /etc/rc.common
# (C) 2024 siltesa

START=20
STOP=15
USE_PROCD=1
PROG=/bin/bash
HAT=/usr/bin/hat.sh
WIFI=/usr/bin/wifi.sh

enable() {
	echo 'enable siltesa HAT'
	start_service
	#$PROG $HAT >/dev/null 2>&1
}
start() {
	echo 'start siltesa HAT'
	start_service
	#$PROG $HAT >/dev/null 2>&1
}

restart() {
	echo 'restart siltesa HAT'
	restart_service
	#$PROG $WIFI >/dev/null 2>&1
}

boot() {
	hat_boot=1
	start "$@"
}

start_service() {
	if [ -n "$hat_boot" ]; then
		# Do not start yet, wait for triggers
		return 0
  	fi
	procd_open_instance
	procd_set_param command "$PROG" -c "$HAT"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

restart_service() {
	# Check if the 'radio0' is down 
	radio0_status=$(wifi status | jq -r '.radio0.up')
	# Check if the 'radio1' is down 
	radio1_status=$(wifi status | jq -r '.radio1.up')
	if [ "$radio0_status" = "false" ] || [ "$radio1_status" = "false" ]; then
		return 0
    fi
	procd_open_instance
	procd_set_param command "$PROG" -c "$WIFI"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	if [ -n "$hat_boot" ]; then
		procd_add_raw_trigger "interface.*.up" 5000 /etc/init.d/hat start
	fi
}
