---
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
ipv6: true
external-ui: "/usr/share/openclash/ui"
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
tcp-concurrent: true
unified-delay: true
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  mmdb: https://github.com/malikshi/geoip/raw/refs/heads/release/Country.mmdb
  geoip: https://github.com/malikshi/v2ray-rules-dat/raw/refs/heads/release/geoip.dat
  geosite: https://github.com/malikshi/v2ray-rules-dat/raw/refs/heads/release/geosite.dat
  asn: https://github.com/malikshi/geoip/raw/refs/heads/release/GeoLite2-ASN.mmdb
global-client-fingerprint: chrome
keep-alive-interval: 15
keep-alive-idle: 600
disable-keep-alive: false
find-process-mode: strict
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:1053
  respect-rules: true
  prefer-h3: true
  use-system-hosts: true
  use-hosts: true
  nameserver:
  - 1.1.1.1
  - "[2606:4700:4700::1111]"
  - https://dns.cloudflare.com/dns-query#h3=true
  - tls://one.one.one.one
  fallback:
  - tls://one.one.one.one
  - https://dns.cloudflare.com/dns-query#h3=true
  - 1.1.1.1
  - "[2606:4700:4700::1111]"
  default-nameserver:
  - 1.1.1.1
  - "[2606:4700:4700::1111]"
  - 1.0.0.1
  - "[2606:4700:4700::1001]"
  proxy-server-nameserver:
  - 1.1.1.1
  - "[2606:4700:4700::1111]"
  - https://dns.cloudflare.com/dns-query#h3=true
  - tls://one.one.one.one
  - 1.0.0.1
  - "[2606:4700:4700::1001]"
sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
  sniff:
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
tun:
  enable: true
  stack: system
  device: utun
  dns-hijack:
  - tcp://any:53
  endpoint-independent-nat: true
  auto-route: false
  auto-detect-interface: false
  auto-redirect: false
  strict-route: false
profile:
  store-selected: true
  store-fake-ip: true
proxy-groups:
- name: ALL-GROUP
  type: select
  disable-udp: false
  url: https://cp.cloudflare.com/generate_204
  interval: 30
  proxies:
  - Traffic-Browsing
  - Traffic-Porn
  - Traffic-Ads
  - Traffic-Gaming
  - FB
  - LB
  - BP
  - DIRECT
  use:
  - Akun
- name: Traffic-Browsing
  type: select
  disable-udp: false
  proxies:
  - FB
  - LB
  - BP
  use:
  - Akun
- name: Traffic-Gaming
  type: select
  disable-udp: false
  proxies:
  - FB
  - LB
  - BP
  use:
  - Akun
- name: Traffic-Porn
  type: select
  disable-udp: false
  proxies:
  - Traffic-Browsing
  - DIRECT
  - REJECT
- name: Traffic-Ads
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - DIRECT
  - Traffic-Browsing
- name: FB
  type: fallback
  disable-udp: false
  use:
  - Akun
  url: https://cp.cloudflare.com/generate_204
  interval: 60
- name: LB
  type: load-balance
  disable-udp: false
  strategy: round-robin
  use:
  - Akun
  url: https://cp.cloudflare.com/generate_204
  interval: 60
- name: BP
  type: url-test
  disable-udp: false
  lazy: false
  use:
  - Akun
  url: https://cp.cloudflare.com/generate_204
  interval: 60
  tolerance: 150
proxy-providers:
  Akun:
    type: file
    path: "./proxy_provider/Akun.yaml"
    health-check:
      enable: true
      url: https://captive.apple.com/generate_204
      interval: 180
rule-providers:
  oisd_big:
    type: http
    behavior: classical
    path: "./rule_provider/oisd_big.yaml"
    url: https://raw.githubusercontent.com/hillz2/openclash_adblock/main/oisd_big.yaml
    interval: 14400
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,ALL-GROUP
- GEOSITE,oisd-nsfw,Traffic-Porn
- GEOSITE,oisd-full,Traffic-Ads
- RULE-SET,oisd_big,Traffic-Ads
- NOT,((DOMAIN-SUFFIX,googlesyndication.com)),Traffic-Ads
- AND,((NETWORK,udp),(OR,(DST-PORT,443),(GEOSITE,youtube))),REJECT
- GEOIP,GOOGLE,ALL-GROUP
- GEOSITE,GOOGLE,ALL-GROUP
- AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,(DOMAIN-KEYWORD,google))),ALL-GROUP
- AND,((NETWORK,UDP),(DST-PORT,5228-5230),(OR,(DOMAIN-KEYWORD,google))),ALL-GROUP
- GEOSITE,rule-gaming,ALL-GROUP
- GEOSITE,rule-indo,ALL-GROUP
- GEOSITE,rule-sosmed,ALL-GROUP
- GEOSITE,rule-streaming,ALL-GROUP
- GEOSITE,rule-speedtest,ALL-GROUP
- GEOSITE,videoconference,ALL-GROUP
- GEOIP,id,ALL-GROUP
